Update main.cpp
mininny/CPPStudy pull request #1
Opened 2020-07-25 17:21 UTC by jaesung-0o0

😉

2020-07-25 17:49 UTC, mininny requested changes
🙏ㅋㅋㅋㅋㅋㅋㅋㅋC++같이 스터디 고고?🏄

2020-07-25 17:49 UTC, mininny commented on CPPStart/CPPStart/main.cpp
> +    x = pow(carrots, 2);
`double x = pow(carrots, 2);`로 사용이 가능합니다!

2020-07-25 17:49 UTC, mininny commented on CPPStart/CPPStart/main.cpp
> +    convertCelsiusToFarenheit();
`numberOfCarrots()`와 `convertCelciusToFarenheit()`은 main함수 상단에서 선언이 되어야할것같습니다

2020-07-25 17:49 UTC, mininny commented on CPPStart/CPPStart/main.cpp
> +    cout << "섭씨 온도를 입력하세요: ";
`using namespace std`가 없어서 에러가 날것같습니다

2020-07-25 17:50 UTC, mininny commented
수정하신거 보니 C의 스멜이 나네요....위험하다....<code><img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png"></code> please

2020-07-26 08:01 UTC, jaesung-0o0 commented on CPPStart/CPPStart/main.cpp
> +    x = pow(carrots, 2);
변수선언을 위로 뽑아보았습니다 ㅎㅎㅎㅎ

2020-07-26 08:02 UTC, jaesung-0o0 commented on CPPStart/CPPStart/main.cpp
> +    cout << "섭씨 온도를 입력하세요: ";
헤헤ㅎ헤헤헤

2020-07-26 08:03 UTC, jaesung-0o0 commented on CPPStart/CPPStart/main.cpp
> +    x = pow(carrots, 2);
C는 변수 선언을 따로 위쪽에 뽑아놓더라구여

2020-07-26 08:03 UTC, jaesung-0o0 commented on CPPStart/CPPStart/main.cpp
> +    convertCelsiusToFarenheit();
히히힣ㅎ힣

2020-07-26 08:20 UTC, mininny commented on CPPStart/CPPStart/main.cpp
> +    cout << "화씨론: " << farenheitFrom(celcius) << endl;
compile error! `Use of undeclared identifier 'farenheitFrom'`

2020-08-01 13:42 UTC, merged

2020-08-01 13:43 UTC, mininny commented
Thanks @jaesung-0o0! 🙇🚀